### PR TITLE
Fix/max leaves

### PR DESCRIPTION
**Pull request by jinlow**
Fixes max leaves bug #32 and makes the booster pickleable.

### CODE REVIEW

**Comment by jinlow** [comment]
@gravesee Adding the ability to pickle a booster, just wanted to run by you, that you didn't see any footguns with this?

**Comment by jinlow** [comment]
The `Booster` object itself can't be directly pickled because it's just a reference to something in memory, so I am dumping the model, and then reloading from that dump.

**Review by gravesee — COMMENTED** [review]
Only thing I'd try different is dumping the file to bytesio (if that is supported) instead of having to write a file, but otherwise looks good to me

**Comment by jinlow** [comment]
> Only thing I'd try different is dumping the file to bytesio (if that is supported) instead of having to write a file, but otherwise looks good to me

Good callout yeah, I don't _think_ that's possible, just because you can only pass a string path to the rust side to use as a file path to save.

**Comment by gravesee** [comment]
Ah yeah, I forgot about that. Can rust return bytes, though? From the serde deserialization?

**Comment by jinlow** [comment]
Good question!
I can look at that, that would be good to have, as a save load option. And then would make dealing with python file like objects easier.

**Comment by jinlow** [comment]
Actually, I could use the `from_json` and `json_dump` methods directly as well. Rather than the save and load methods.

**Comment by gravesee** [comment]
The nice thing about bytes is that they're pickleable. that was my original motivation but definitely not a requirement!

**Comment by jinlow** [comment]
OK, this seems cleaner, thanks for the suggestion!

**Pull request merged**
