### PR TITLE
Feature/calc init

### PR DESCRIPTION
**Pull request by gravesee**

### CODE REVIEW

**Comment by gravesee** [comment]
@jinlow I couldn't get the xgboost and forust predictions to match greater than tolerance `0.001` for the `SquaredLoss` with `initialize_base_score=True` test. It matches to the thousandth's place...

**Review by jinlow — APPROVED** [review]
This is fabulous! Thanks!
Do you think we should default this parameter to True? Unless there is a reason to not? It would just mean adding `intialize_base_score` to False in all the test. We could even just set it in the python package if that was easier.

**Comment by jinlow** [comment]
Or does it make more sense to leave it as False, so folks can “opt in”?

**Comment by jinlow** [comment]
Or, we set initialize_base_score to false, and then now or in a separate pull request make base score an optional, but only for the new method/__init__. Then in there we check if base_score is none, and if it is, we set initialize_base_score to true, and use our default base score of 0.5 on the booster, knowing it will be corrected at fit time. So base_score still stays just a straight f64 on the booster.

**Pull request merged**
